---
- greeting:
    text_size: xl
    text: Home Server

- resources:
    cpu: true
    memory: true
    uptime: true

- datetime:
    text_size: l
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h12

- search:
    provider: google
    target: _blank
